### ISSUE TITLE
helm integration

### ISSUE THREAD

**Issue by myrgy** [ffevotte/multi-compile#1]
Hello,

awesome plugin! is it possible to switch from hydra to move usual helm?
I think some people will ask about ivy integration!

Looking forward to hearing from you.

**Comment by ffevotte** [comment]
Hello,

thanks for your comment, and sorry for the long delay.

What do you have in mind exactly regarding an helm interface to multi-compile? Currently, hydra is used to build an interactive menu (*à la* magit) dispatching between several predefined commands. I see helm (or ivy) more as a way to select between numerous candidates (computed on the fly), and then act on them (optionally selecting one of several predefined commands). These seem to be rather different purposes.

Do you propose to list all available sub-commands in `XXX-dwim` as candidates among which to choose in helm? which would display something like the following:

```
 check:                                                                        
 recompile                                                                     
 interactive
 reset everything
 recompile and change command
 recompile and change directory
```
```
 *check-dwim* L1    [5 Candidate(s)]   C-h m:Help TAB:Act RET/f1/f2/f-n:NthAct C
 pattern: 
```

This would be very doable, but it looks (to me) like a bit of a regression with respect to hydra: you have to type a few characters to select an option (or move point with <kbd>C-n</kbd>/<kbd>C-p</kbd> or arrows or whatever), then select it with <kbd>RET</kbd>. Using hydra instead, users only have to type one key to select an option.

But this might be only me. Would you find such an helm interface more usable? Or did I completely misunderstand your proposal?

**Comment by myrgy** [comment]
here is an example ctest helm integration: https://github.com/danlamanna/helm-ctest
In general it does the same thing, but many people use avy or helm.
As for me - helm is common completion for action (I use spacemacs)

**Comment by ffevotte** [comment]
Sorry, but I still don't understand what you propose.

What would you list in helm ?
1. all possible actions (a static list of 5 candidates as currently proposed in the hydra menu)
2. all defined compilation commands (and then have helm F1/F2/Fn actions to replace the current hydra menu)
3. all existing make targets / ctest tests, etc (which would be a new feature altogether)

I initially thought you meant option 1, but seeing your answer I'm not so sure.

**Comment by myrgy** [comment]
yes, I was talking about first item - list all possible actions 
UPD: I was talking about integration, like this https://github.com/ReanGD/emacs-multi-compile

**Comment by ffevotte** [comment]
I just introduced in branch [issue1](/ffevotte/multi-compile/tree/issue1) a basic implementation of an helm-based menu.

You should be able to test it relatively simply  by manually evaluating the update `multi-compile.el` file and using a configuration stanza like the following:

```emacs-lisp
(setq multi-compile-dwim-method 'helm)
(global-set-key
 (kbd "<f5>")
 (multi-compile
  check
  :command "echo foo"))
```

Then, pressing <kbd>C-u</kbd><kbd>f5</kbd> offers to select an action using helm, like in the following screenshot:

![multi-compile_dwim-helm](https://user-images.githubusercontent.com/376712/44492723-d62d4980-a665-11e8-8013-76ebc145881c.png)

Is this what you wanted?

**Comment by myrgy** [comment]
I gave a try, but was not able to trigger helm view. When I pressed F5 helm doesn't appear. I see only "foo" in compilation window. Do you have any idea how to fix it?
One more thing - I noticed that you don't use require helm.
I use use-package to load file.

**Comment by ffevotte** [comment]
The menu only appears when you provide a prefix argument, i.e. <kbd>C-u</kbd><kbd>F5</kbd> in stock emacs (I'm not sure if it is the same with spacemacs). Have you tried that?

And you're right, I haven't yet taken care of requiring helm or hydra depending on user settings, so you might have to manually require it in order to test (but I would think helm is already loaded in your environment since you seem to use it for other purposes). In a first stage, I wanted to check that I was able to correctly introduce the feature you requested.

In a second stage, I'll have to tidy things up, ensure all required packages are correctly loaded, and setup some test cases. But this will come later, when I'm sure the feature does what you want it to do.

**Comment by myrgy** [comment]
Hi there!

I gave a second try and now it works. Originally I was not able to activate helm menu because I use evil, so I had to enable insert mode only only after that press `C-u F5`
